# Generated by Django 6.0.1 on 2026-01-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apartament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Счетчик', to='core.apartament')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Показание, кВт·ч')),
                ('date', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Показания_счетчика', to='core.meter')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('meter', 'date')},
            },
        ),
    ]
